### ISSUE TITLE
Update to the latest stable version of flutter or run an error

### ISSUE THREAD

**Issue by huangcs427** [LucJosin/on_audio_query#78]
Version info:
> Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (3 days ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

Error:
> e: C:\Data\flutter\.pub-cache\hosted\pub.flutter-io.cn\on_audio_query-2.6.0\android\src\main\kotlin\com\lucasjosino\on_audio_query\OnAudioQueryPlugin.kt: (38, 1): Class 'OnAudioQueryPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Data\flutter\.pub-cache\hosted\pub.flutter-io.cn\on_audio_query-2.6.0\android\src\main\kotlin\com\lucasjosino\on_audio_query\OnAudioQueryPlugin.kt: (148, 5): 'onRequestPermissionsResult' overrides nothing
>
> FAILURE: Build failed with an exception.

**Comment by Pierre2tm** [comment]
Get the same problem after upgrading to 3.0

**Comment by MtiPsd** [comment]
> 

get the same problem with flutter 3.0
